/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasitha
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Hasitha\\Documents\\NetBeansProjects\\TimeTableManagementSystem\\src\\timetablemanagementsystem\\hasi.png"));
        initComponents();
        
        // create the dialog box as middle and attractfull
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        blank_userID = new javax.swing.JLabel();
        blank_password = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 370, 120, 23);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 450, 160, 23);

        userID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userIDKeyReleased(evt);
            }
        });
        jPanel1.add(userID);
        userID.setBounds(330, 370, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TIME TABLE MANAGEMENT SYSTEM");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 0, 710, 70);

        jLabel4.setFont(new java.awt.Font("UnitedStates", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        jLabel4.setAlignmentX(2.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 300, 330, 40);

        signin.setFont(new java.awt.Font("UnitedStates", 1, 14)); // NOI18N
        signin.setForeground(new java.awt.Color(153, 0, 204));
        signin.setText("SIGN IN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });
        jPanel1.add(signin);
        signin.setBounds(380, 520, 120, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/1.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 40, 340, 230);

        Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordKeyReleased(evt);
            }
        });
        jPanel1.add(Password);
        Password.setBounds(330, 450, 200, 30);

        blank_userID.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        blank_userID.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(blank_userID);
        blank_userID.setBounds(330, 410, 200, 20);

        blank_password.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        blank_password.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(blank_password);
        blank_password.setBounds(330, 490, 200, 20);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/background2.jpg"))); // NOI18N
        background.setText("SIGN UP");
        jPanel1.add(background);
        background.setBounds(0, -10, 710, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
        if(userID.getText().trim().isEmpty() && Password.getText().trim().isEmpty()){
            blank_userID.setText("UserID is Empty");
            blank_password.setText("Password is Empty");
        } 
        else if(userID.getText().trim().isEmpty()){
            blank_userID.setText("UserID is Empty");
            
        }  
        else if(Password.getText().trim().isEmpty()){
           
            blank_password.setText("Password is Empty");
        }  
        else{
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3310/timetablemanagement","root","");
            String sql = "Select * from signupdetails where Member_number=? and petNames=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, userID.getText());
            pst.setString(2, Password.getText());

            ResultSet rs = pst.executeQuery();
            
            
            
            KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
            keyGenerator.init(128);
            SecretKey secretKey = keyGenerator.generateKey();    
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            char[] password = Password.getPassword();
            byte[] passwordBytes = new String(password).getBytes();
            byte[] encryptedPasswordBytes = cipher.doFinal(passwordBytes);
            cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.DECRYPT_MODE, secretKey);
            byte[] decryptedPasswordBytes = cipher.doFinal(encryptedPasswordBytes);
            String encryptedPassword = new String(encryptedPasswordBytes);
            
            

            

            if(rs.next()){
                String position = rs.getString("Position");
//                System.out.println(position);
            JOptionPane.showMessageDialog(null, "Welcome the TimeTabelManagement System");
            if(position.equals("Admin")){
            int addnew = JOptionPane.showConfirmDialog(null, "Do you want to add new members","Warning",JOptionPane.YES_NO_OPTION);
            
                    if(addnew==JOptionPane.YES_OPTION){
                            Signup sign = new Signup();
                            this.setVisible(false);
                            sign.setVisible(true);
                            
                        }
                    else{
                            Dashboard login = new Dashboard();
                            this.setVisible(false);
                            login.setVisible(true);
                            
                    }
            }
                    else{
                            Dashboard login = new Dashboard();
                            this.setVisible(false);
                            login.setVisible(true);
                            
                        }
            }
            
            
            else{
                JOptionPane.showMessageDialog(null, "Username or Password are Incorrect");
                userID.setText("");
                Password.setText("");
            }
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
    }//GEN-LAST:event_signinActionPerformed

    private void userIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userIDKeyReleased
        // TODO add your handling code here:
         blank_userID.setText("");
        
    }//GEN-LAST:event_userIDKeyReleased

    private void PasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordKeyReleased
        // TODO add your handling code here:
        blank_password.setText("");
    }//GEN-LAST:event_PasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login l = new Login();
                l.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel background;
    private javax.swing.JLabel blank_password;
    private javax.swing.JLabel blank_userID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signin;
    private javax.swing.JTextField userID;
    // End of variables declaration//GEN-END:variables
}
