/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasitha
 */
public class ReportingModule extends javax.swing.JFrame {

    /**
     * Creates new form ReportingModule
     */
    public ReportingModule() {
         this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Hasitha\\Documents\\NetBeansProjects\\TimeTableManagementSystem\\src\\timetablemanagementsystem\\hasi.png"));
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resourceutilization = new javax.swing.JButton();
        timetable = new javax.swing.JButton();
        classroomusages = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        final_table = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REPORTING MODULE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 660, 40);

        resourceutilization.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resourceutilization.setText("RESOURCE_UTILIZATION");
        jPanel1.add(resourceutilization);
        resourceutilization.setBounds(180, 340, 310, 25);

        timetable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timetable.setText("SCHEDULED TIME_TABLE");
        timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetableActionPerformed(evt);
            }
        });
        jPanel1.add(timetable);
        timetable.setBounds(180, 150, 310, 25);

        classroomusages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        classroomusages.setText("CLASSROOM_USAGES ");
        jPanel1.add(classroomusages);
        classroomusages.setBounds(180, 240, 310, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 480, 73, 25);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/background2.jpg"))); // NOI18N
        jPanel1.add(back);
        back.setBounds(1, -4, 670, 520);

        final_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "123", "123", "123", "123", "123", "123"},
                {"111", "111", "111", "111", "111", "1111", "555"}
            },
            new String [] {
                "Date", "Time", "Subject", "Subject_code", "Instructor", "Class", "no_of_Student"
            }
        ));
        jScrollPane2.setViewportView(final_table);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 540, 1050, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void timetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetableActionPerformed
        // TODO add your handling code here:
        String path ="";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        
        if(x ==JFileChooser.APPROVE_OPTION){
            path = j.getSelectedFile().getPath();
        }
        
        Document doc = new Document();
        
        try {
            PdfWriter writer = PdfWriter.getInstance(doc,new FileOutputStream(path+"\\sample.pdf"));
            doc.open();
            PdfPTable tbl = new PdfPTable(7);
            tbl.addCell("Date");
            tbl.addCell("Time");
            tbl.addCell("Subject");
            tbl.addCell("Subject_Code");
            tbl.addCell("Instructor");
            tbl.addCell("Class_name");
            tbl.addCell("No_OF_Student");
             
             for(int i=0; i<final_table.getRowCount(); i++){
                 String Date = final_table.getValueAt(i, 0).toString();
                 String Time = final_table.getValueAt(i, 1).toString();
                 String Subject = final_table.getValueAt(i, 2).toString();
                 String Subject_Code = final_table.getValueAt(i, 3).toString();
                 String Instructor = final_table.getValueAt(i, 4).toString();
                 String Class = final_table.getValueAt(i, 5).toString();
                 String Sstudent = final_table.getValueAt(i, 6).toString();
                 
                 tbl.addCell(Date);
                 tbl.addCell(Time);
                 tbl.addCell(Subject);
                 tbl.addCell(Subject_Code);
                 tbl.addCell(Instructor);
                 tbl.addCell(Class);
                 tbl.addCell(Sstudent);
                            
             }
             
             doc.add(tbl);
             JOptionPane.showMessageDialog(null, "Download PDF file", "Alert Msg", JOptionPane.WARNING_MESSAGE);
             doc.close();
             writer.close();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ReportingModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ReportingModule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_timetableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportingModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportingModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton classroomusages;
    private javax.swing.JTable final_table;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resourceutilization;
    private javax.swing.JButton timetable;
    // End of variables declaration//GEN-END:variables
}
