/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasitha
 */
public class Signup extends javax.swing.JFrame {
    
    public void ClearFields(){
        
        text1.setText(null);
        text2.setText(null);
        text3.setText(null);
        text4.setText(null);
        text5.setText(null);
        text6.setText(null);
        text7.setText(null);
        text8.setText(null);
    }
    

    /**
     * Creates new form SIGHUP
     */
    public Signup() {
         this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Hasitha\\Documents\\NetBeansProjects\\TimeTableManagementSystem\\src\\timetablemanagementsystem\\hasi.png"));
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JPasswordField();
        text8 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        text9 = new javax.swing.JComboBox<>();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        showpsw = new javax.swing.JCheckBox();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN-UP DETAILS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 30, 250, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name with Initials : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name            : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 130, 130, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email                   :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 170, 120, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password              : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 360, 130, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 400, 130, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Faculty                :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 210, 120, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Department         : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 250, 120, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member's Number :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 290, 130, 17);
        jPanel1.add(text1);
        text1.setBounds(180, 82, 370, 30);
        jPanel1.add(text2);
        text2.setBounds(180, 122, 370, 30);
        jPanel1.add(text3);
        text3.setBounds(180, 162, 370, 30);
        jPanel1.add(text4);
        text4.setBounds(180, 202, 370, 30);
        jPanel1.add(text5);
        text5.setBounds(180, 242, 370, 30);
        jPanel1.add(text6);
        text6.setBounds(180, 282, 370, 30);
        jPanel1.add(text7);
        text7.setBounds(180, 360, 370, 30);
        jPanel1.add(text8);
        text8.setBounds(180, 400, 370, 30);

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Position                  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 330, 130, 16);

        text9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text9.setForeground(new java.awt.Color(240, 240, 240));
        text9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff", "Faculty_Member" }));
        jPanel1.add(text9);
        text9.setBounds(180, 322, 370, 30);

        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm);
        confirm.setBounds(459, 490, 90, 25);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(319, 490, 100, 25);

        showpsw.setBackground(new java.awt.Color(0, 0, 0));
        showpsw.setForeground(new java.awt.Color(255, 255, 255));
        showpsw.setText("Show Password");
        showpsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpswActionPerformed(evt);
            }
        });
        jPanel1.add(showpsw);
        showpsw.setBounds(403, 440, 150, 25);

        background3.setForeground(new java.awt.Color(255, 255, 255));
        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetablemanagementsystem/background2.jpg"))); // NOI18N
        jPanel1.add(background3);
        background3.setBounds(1, -4, 600, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpswActionPerformed
        // TODO add your handling code here:
        if(showpsw.isSelected()){
            text7.setEchoChar((char)0);
            text8.setEchoChar((char)0);
        }
        else{
            text7.setEchoChar('*');
            text8.setEchoChar('*');
        }
    }//GEN-LAST:event_showpswActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(text1.getText().equals("") || text2.getText().equals("") || text3.getText().equals("") || text4.getText().equals("") || text5.getText().equals("") || text6.getText().equals("") || text7.getText().trim().isEmpty() || text8.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this,"Please Fill required Fields");
        }
        else{
            try{
            KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
            keyGenerator.init(128);
            SecretKey secretKey = keyGenerator.generateKey();    
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            char[] password = text7.getPassword();
            byte[] passwordBytes = new String(password).getBytes();
            byte[] encryptedPasswordBytes = cipher.doFinal(passwordBytes);
            cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.DECRYPT_MODE, secretKey);
            byte[] decryptedPasswordBytes = cipher.doFinal(encryptedPasswordBytes);
            String encryptedPassword = new String(encryptedPasswordBytes);
            String decryptedPassword = new String(decryptedPasswordBytes);
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3310/timetablemanagement","root","");
            String sql = "insert into signupdetails (Name_With_Initial,Full_Name,Email,Faculty,Department,Member_number,Position,Password,petNames) values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, text1.getText());
            pst.setString(2, text2.getText());
            pst.setString(3, text3.getText());
            pst.setString(4, text4.getText());
            pst.setString(5, text5.getText());
            pst.setString(6, text6.getText());
            pst.setString(7, text9.getItemAt(text9.getSelectedIndex()));
            pst.setString(8, encryptedPassword);
            pst.setString(9, decryptedPassword);
           
            
            pst.executeUpdate();
            
            // for backup purpose
            Class.forName("com.mysql.jdbc.Driver");
            Connection con_backup = DriverManager.getConnection("jdbc:mysql://localhost:3310/timetablemanagementbackup","root","");
            String sql_backup = "insert into signupdetails (Name_With_Initial,Full_Name,Emial,Faculty,Department,Members_Number,Position,Password,petName) values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst_backup = con_backup.prepareStatement(sql_backup);
            pst_backup.setString(1, text1.getText());
            pst_backup.setString(2, text2.getText());
            pst_backup.setString(3, text3.getText());
            pst_backup.setString(4, text4.getText());
            pst_backup.setString(5, text5.getText());
            pst_backup.setString(6, text6.getText());
            pst_backup.setString(7, text9.getItemAt(text9.getSelectedIndex()));
            pst_backup.setString(8, encryptedPassword);
            pst_backup.setString(9, decryptedPassword);
           
            
            pst_backup.executeUpdate();
            
            // backup is over
         
            JOptionPane.showMessageDialog(this, "Row Is created Successfully");
            ClearFields();
//            updateDB();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            
//        Login log = new Login();
//        JOptionPane.showMessageDialog(log, "Created an new account!");
//        log.setVisible(true);
//        this.setVisible(false);
            
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        this.setVisible(false);
        dash.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                 
                Signup l = new Signup();
               
                l.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background3;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox showpsw;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JPasswordField text7;
    private javax.swing.JPasswordField text8;
    private javax.swing.JComboBox<String> text9;
    // End of variables declaration//GEN-END:variables
}
